### ISSUE TITLE
AttributeError: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by mattmofr** [vash3d/pigpio_encoder#1]
Hello vash3d,
Thanks for your library.
I encountered an error which seems to be linked to list.clear() function which is a python3 function while pigpio_encoder is installed on python2.7 distribution libraries with pip.

Here is the terminal output

`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/pigpio.py", line 1181, in run
    cb.func(cb.gpio, newLevel, tick)
  File "/usr/local/lib/python2.7/dist-packages/pigpio_encoder/pigpio_encoder.py", line 61, in dt_fall
    self.sequence.clear()
AttributeError: 'list' object has no attribute 'clear'`

Maybe I'm doing something wrong. Let me know if its an issue on my side.

Best regard,

mm

**Comment by vash3d** [comment]
Thanks for reporting the issue.
I've added python 3 requirements to Readme, however it was specified on Classifiers on pypi.
