### ISSUE TITLE
 ImportError: cannot import name 'Rotary' from 'pigpio_encoder'

### ISSUE THREAD

**Issue by Khamull** [vash3d/pigpio_encoder#16]
So, apparently, I got something backwards,
Did the installations steps as the readme file states, copied the samples and I got this output:

ImportError: cannot import name 'Rotary' from 'pigpio_encoder' (/home/pi/.local/lib/python3.7/site-packages/pigpio_encoder/__init__.py)

My code looks like this:

```
from pigpio_encoder import Rotary

def rotary_callback(counter):
    print("Counter value: ", counter)

def sw_short():
    print("Switch pressed")

def up_callback():
    print("Up rotation")

def down_callback():
    print("Down rotation")

my_rotary = Rotary(clk=27, dt=22, sw=17)
my_rotary.setup_rotary(
        rotary_callback=rotary_callback,
        up_callback=up_callback,
        down_callback=down_callback,
        )
my_rotary.setup_switch(sw_short_callback=sw_short)

my_rotary.watch()
```

Now, if I do:

```
from pigpio_encoder import pigpio_encoder
...
my_rotaryi = pigpio_encoder.Rotary(clk=27, dt=22, sw=17)
```

It runs with no issues but, the up_callback and down_callback do not work, or at least, nothing is displayed for them, but the counter works just fine!
Image attached is from the counter working with the basic config as the samples here on github!
![CounterWorking](https://user-images.githubusercontent.com/5778404/121390110-6f1ad580-c923-11eb-9d98-4dac49a31253.PNG)

**Comment by Khamull** [comment]
After some more testing, I got to the following situation!
If I remove the current version I got installed and do a 
`pip install git+https://github.com/vash3d/pigpio_encoder.git`

 I got a greater version then if I just use
 
` pip install pigpio_encoder`

However, in the second case, the up/down callbacks are not implementes(it seems) and in the firts, the issue is different!
Giving even the message that we do not have pigpio_enconder installed!

**Comment by volkerjaenisch** [comment]
@Khamull Thank you for the findings. The version mismatch is because I have taken over as maintainer of this package. But the former maintainer has not given me the credintials to publish a new version  to PyPI. 
So please use the version from GH and not from PyPI.
I will setup a testbench tomorrow and come back to you.

**Comment by volkerjaenisch** [comment]
@Khamull Can you please check the new version.
Please have a look at the main.py - the callbacks now have a counter parameter.

```
from pigpio_encoder import Rotary

def rotary_callback(counter):
    print("General rotation")
    print("Counter value: ", counter)

def sw_short():
    print("Switch pressed")

def up_callback(counter):
    print("Up rotation")
    print("Counter value: ", counter)

def down_callback(counter):
    print("Down rotation")
    print("Counter value: ", counter)

my_rotary = Rotary(clk_gpio=13, dt_gpio=19, sw_gpio=26)
my_rotary.setup_rotary(
        rotary_callback=rotary_callback,
        up_callback=up_callback,
        down_callback=down_callback,
        )
my_rotary.setup_switch(sw_short_callback=sw_short)

my_rotary.watch()
```

```
pi@raspberrypi:~/workspace/pigpio_encoder/src $ python3 main.py
Down rotation
Counter value:  0
Down rotation
Counter value:  0
Down rotation
Counter value:  0
Down rotation
Counter value:  0
Down rotation
Counter value:  0
General rotation
Counter value:  1
Up rotation
Counter value:  1
General rotation
Counter value:  2
Up rotation
Counter value:  2
General rotation
Counter value:  3
Up rotation
Counter value:  3
General rotation
Counter value:  4
Up rotation
Counter value:  4
General rotation
Counter value:  5
Up rotation
Counter value:  5
```

**Comment by Khamull** [comment]
I've usede pip uninstall pigpio_encoder, and then did 
`pip install git+https://github.com/vash3d/pigpio_encoder.git`
Attached are my results so far, it does not seems to locate the pigpio_encoder!
![image](https://user-images.githubusercontent.com/5778404/121537531-633e1a80-c9da-11eb-8ddc-6f0b11b3cf66.png)
![image](https://user-images.githubusercontent.com/5778404/121537715-8d8fd800-c9da-11eb-9b30-f95a4d2095c1.png)
![image](https://user-images.githubusercontent.com/5778404/121538283-0e4ed400-c9db-11eb-9b77-ccffed3f65ab.png)

**Comment by Khamull** [comment]
![image](https://user-images.githubusercontent.com/5778404/121538750-67b70300-c9db-11eb-8752-063616944c4f.png)
Tested from console as well, and got the same result!

**Comment by volkerjaenisch** [comment]
@Khamull Please do not send screenshots instead copy the textual screen content.  Ok I can reproduce your problem. Please stay tuned.

**Comment by volkerjaenisch** [comment]
@Khamull  Please try the following:

`python3 -mpip install --upgrade git+https://github.com/vash3d/pigpio_encoder.git@deploy`


```
python3
>>> from pigpio_encoder.rotary import Rotary
```

Please not the different import!

If this scheme works for you also I will merge this into the master branch.

**Comment by Khamull** [comment]
@volkerjaenisch, just tested as you instructed and worked with no issues now!
Below is the code
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pigpio_encoder.rotary import Rotary

def rotary_callback(counter):
    print("General rotation")
    print("Counter value: ", counter)

def sw_short():
    print("Switch pressed")

def up_callback(counter):
    print("Up rotation")
    print("Counter value: ", counter)

def down_callback(counter):
    print("Down rotation")
    print("Counter value: ", counter)

my_rotary = Rotary(clk_gpio=22, dt_gpio=27, sw_gpio=17)
my_rotary.setup_rotary(
        rotary_callback=rotary_callback,
        up_callback=up_callback,
        down_callback=down_callback,
        )
my_rotary.setup_switch(sw_short_callback=sw_short)

my_rotary.watch()
```

And here is my output

In [14]: runfile('/home/pi/RotaryPiTest/STDOUTTestII.py', wdir='/home/pi/RotaryPiTest')
General rotation
Counter value:  10
Down rotation
Counter value:  10
General rotation
Counter value:  10
Down rotation
Counter value:  10
General rotation
Up rotation
Counter value:  1
General rotation
Counter value:  18
Up rotation
Counter value:  18
General rotation
Counter value:  9
Down rotation
Counter value:  9
General rotation
Counter value:  9
Down rotation
Counter value:  9
General rotation
Up rotation
Counter value:  2
General rotation
Counter value:  19
Up rotation
Counter value:  19
General rotationGeneral rotation
Counter value:  20
Up rotation
Counter value:  20
General rotation
Counter value:  8
Down rotation
Counter value:  8

Counter value:  8
Down rotation
Counter value:  8
General rotation
Up rotation
Counter value:  3
General rotationGeneral rotation
Counter value:  21
Up rotation
Counter value:  21
General rotation
Counter value:  7
Down rotation
Counter value:  7

Counter value:  7
Down rotation
Counter value:  7
General rotation
Up rotation
Counter value:  4
General rotationGeneral rotation
Counter value:  6
Down rotation
Counter value:  6

Counter value: General rotation
Counter value:  6
Down rotation
Counter value:  6
General rotation
Up rotation
 22
Up rotation
Counter value:  22
Counter value:  5
General rotationGeneral rotation
Counter value:  23
Up rotation
Counter value:  23

Counter value:  5
Down rotation
Counter value:  5
General rotationGeneral rotation
Counter value:  5
Down rotation
Counter value:  5

Up rotation
Counter value:  6
General rotationGeneral rotationGeneral rotation
Counter value:  4
Down rotation
Counter value:  4

Counter value:  4
Down rotation
Counter value:  4
General rotation
Up rotation
Counter value:  7

Counter value:  24
Up rotation
Counter value:  24
General rotationGeneral rotationGeneral rotation
Counter value:  3
Down rotation
Counter value:  3

Counter value:  3
Down rotation
Counter value:  3
General rotation
Counter value:  25
Up rotation
Counter value:  25

Up rotation
Counter value:  8
General rotation
Counter value:  2
Down rotation
Counter value:  2
General rotationGeneral rotation
Counter value:  2
Down rotation
Counter value:  2

Up rotation
Counter value:  9
General rotation
Counter value:  26
Up rotation
Counter value:  26
General rotationGeneral rotation
Counter value:  1
Down rotation
Counter value:  1
General rotation
Up rotation
Counter value:  10
General rotation
Counter value:  1
Down rotation
Counter value:  1

Counter value:  27
Up rotation
Counter value:  27
General rotationGeneral rotation
Counter value:  26
Down rotation
General rotation
Counter value:  2
Up rotation
Counter value:  2

Counter value:  2
Up rotation
Counter value:  2
Counter value:  26
General rotation
Down rotation
Counter value:  9
General rotationGeneral rotation
Counter value:  25
Down rotation
Counter value:  25
General rotation
Counter value:  3
Up rotation
Counter value:  3
General rotation
Down rotation
Counter value:  8

Counter value:  3
Up rotation
Counter value:  3
General rotationGeneral rotation
Counter value:  24
Down rotation
Counter value:  24
General rotation
Down rotation

Counter value:  4
Up rotation
Counter value:  4
Counter value:  7
General rotation
Counter value:  4
Up rotation
Counter value:  4
General rotationGeneral rotation
General rotation
Down rotation
Counter value:  6
Counter value:  5
Up rotation
Counter value:  5

Counter value:  23
Down rotation
Counter value:  23
General rotation
Counter value:  5
Up rotation
Counter value:  5
General rotationGeneral rotation
Counter value:  22
Down rotation
Counter value:  22
General rotation
Counter value:  6
Up rotation
Counter value:  6

Counter value:  6
Up rotation
Counter value:  6
General rotation
Down rotation
Counter value:  5
General rotationGeneral rotation
Counter value:  21
Down rotation
Counter value:  21

Counter value:  7
Up rotation
Counter value:  7
General rotation
Down rotation
Counter value:  4
General rotation
Counter value:  7
Up rotation
Counter value:  7
General rotationGeneral rotation
Down rotation
Counter value:  3

Counter value:  8
Up rotation
Counter value:  8
General rotationGeneral rotation
Counter value:  8
Up rotation
Counter value:  8

Counter value:  20
Down rotation
Counter value:  20
General rotationGeneral rotationGeneral rotation
Down rotation
Counter value:  2
General rotation
Counter value:  9
Up rotation
Counter value:  9

Counter value:  9
Up rotation
Counter value:  9

Counter value:  19
Down rotation
Counter value:  19
General rotationGeneral rotation

**Comment by volkerjaenisch** [comment]
Current Version 0.2.4 is now available on PyPI.

**Comment by Khamull** [comment]
Thank you for the hard work! As I mentioned, it worked!
