### ISSUE TITLE
Master of the repository?

### ISSUE THREAD

**Issue by volkerjaenisch** [vash3d/pigpio_encoder#6]
Dear @vash3d!

Thank you very much for accepting my pullrequest and to give me admin access to this repo.

Since there was no much conversation I accepted my own last pull request.

Is this OK for you? Please give me a hint what you are intending with this repo and what the rules are to mess with it.

If you like me to become the maintainer I am willing to do so.

Cheers,

Volker

**Comment by vash3d** [comment]
Hi Volker, sorry for the late reply. 
I’ll be glad if you’ll became the maintainer of the project. Unfortunately I’ve not much time to follow it as I should. 
I will check out from time to time and I hope I can contribute again in a near future

**Comment by volkerjaenisch** [comment]
Dear @vash3d 
I notice that I have no access to the pypi repository for pigpio_encoder. 
Can you please grant me access.
Cheers.
Volker

**Comment by vash3d** [comment]
Sure! I just need your username on pypi

**Comment by volkerjaenisch** [comment]
Thank you so much!
My username is volkerjaenisch

**Comment by vash3d** [comment]
Done. Sorry for the delay

**Comment by volkerjaenisch** [comment]
Can you please also include me in test.pypi.org, so I can test the new release forehand. 
Sorry for bothering you.

**Comment by volkerjaenisch** [comment]
Thank you so much for the short response time!

**Comment by volkerjaenisch** [comment]
Can you please also give me the manager role so I can delete a bad version.
